### PR TITLE
Create setup.py to install as a script.

### PR DESCRIPTION
**Pull request by vhugo**
Added setup.py and test on Linux, but should work anywhere setup is supported. Install script  and package data `templates/*.jinja`. 

This is the result of my test with pip:
```
root@d2543a057315:/# pip install har2jmeter/
Collecting jinja2>=2.7.3 (from har2jmeter==0.1)
  Downloading https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl (126kB)
    100% |████████████████████████████████| 133kB 4.5MB/s
Collecting MarkupSafe>=0.23 (from jinja2>=2.7.3->har2jmeter==0.1)
  Downloading https://files.pythonhosted.org/packages/4d/de/32d741db316d8fdb7680822dd37001ef7a448255de9699ab4bfcbdf4172b/MarkupSafe-1.0.tar.gz
Building wheels for collected packages: har2jmeter, MarkupSafe
  Running setup.py bdist_wheel for har2jmeter ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-JYcujO/wheels/4b/1c/59/a69d3cb46a693578104e640ef6e42bbb128292df4586f1cb10
  Running setup.py bdist_wheel for MarkupSafe ... done
  Stored in directory: /root/.cache/pip/wheels/33/56/20/ebe49a5c612fffe1c5a632146b16596f9e64676768661e4e46
Successfully built har2jmeter MarkupSafe
Installing collected packages: MarkupSafe, jinja2, har2jmeter
Successfully installed MarkupSafe-1.0 har2jmeter-0.1 jinja2-2.10

root@d2543a057315:/# which har2jmeter.py
/usr/local/bin/har2jmeter.py

root@d2543a057315:/# ls -las /usr/local/templates/
total 12
4 drwxr-sr-x 2 root staff 4096 Oct 23 02:24 .
4 drwxrwsr-x 1 root staff 4096 Oct 23 02:24 ..
4 -rw-r--r-- 1 root staff 3933 Oct 23 02:24 jmeter.jinja
```

This will solve #2

### CODE REVIEW

**Comment by dmonego** [comment]
Have you tried it using virtualenv? Using a virtualenv environment on mac OS I'm able to install it, but when I run it against the test data I get the following:

```
(venv) ✔ ~/code/tmp/har2jmeter [install_as_script|…7] 
16:50 $ har2jmeter.py test-data/stackoverflow.com.har 
Traceback (most recent call last):
  File "/Users/mm30141/venv/bin/har2jmeter.py", line 4, in <module>
    __import__('pkg_resources').run_script('har2jmeter==0.1', 'har2jmeter.py')
  File "/Users/mm30141/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 750, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/mm30141/venv/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1534, in run_script
    exec(script_code, namespace, namespace)
  File "/Users/mm30141/venv/lib/python2.7/site-packages/har2jmeter-0.1-py2.7.egg/EGG-INFO/scripts/har2jmeter.py", line 41, in <module>
    
  File "/Users/mm30141/venv/lib/python2.7/site-packages/har2jmeter-0.1-py2.7.egg/EGG-INFO/scripts/har2jmeter.py", line 18, in har2jmeter
    
  File "/Users/mm30141/venv/lib/python2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 830, in get_template
    return self._load_template(name, self.make_globals(globals))
  File "/Users/mm30141/venv/lib/python2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/environment.py", line 804, in _load_template
    template = self.loader.load(self, name, globals)
  File "/Users/mm30141/venv/lib/python2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/loaders.py", line 113, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "/Users/mm30141/venv/lib/python2.7/site-packages/Jinja2-2.10-py2.7.egg/jinja2/loaders.py", line 187, in get_source
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: jmeter.jinja
```

**Comment by dmonego** [comment]
Thanks for the hard work!

**Comment by vhugo** [comment]
I've merged the new changes and add a new change that should fix the problem you had while testing with virtualenv. Can you please give it another try?

**Comment by dmonego** [comment]
Thanks for the changes! I've moved a couple things around to get it working in multiple environments, and it now installs the template and the loading code as part of a package.

**Pull request merged**
